# Generated by Django 5.0.1 on 2024-02-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_post_options_post_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postx',
        ),
    ]
