# Generated by Django 5.0.1 on 2024-02-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_post_postx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postx',
            new_name='Post',
        ),
    ]
