# Generated by Django 5.0.1 on 2024-02-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_postx_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
